DN_WEAPON_TYPES = [
  'Greatsword',
  'Gauntlet',
  'Axe',
  'Hammer',
  'Shortbow',
  'Longbow',
  'Crossbow',
  'Quiver',
  'Book',
  'Orb',
  'Puppet',
  'Mace',
  'Flail',
  'Wand',
  'Shield',
  'Quiver',
  'Cannon',
  'Bubble Blaster',
  'Powerglove',
  'Fan',
  'Chakram',
  'Focus',
  'Scimtar',
  'Dagger',
  'Hook',
  'Spear',
  'Scythe', # ABSOLUTELY NO CLUE WHAT THIS IS, BUT IT'S THE OTHER SIDE OF LENCEA
  'Bracelet'
]