#!/bin/sh

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

cd $DIR

## mogrify should be done in cwd
#cd dnss-web/src/main/webapp/resources/images
#mogrify -crop 512x550+0+0 +repage +repage -path ../min/images skillicon*.png

# crush pngs
#cd ../min/images
#for file in *; do
#  pngcrush -ow ${file}
#done