#!/bin/bash
PATH=$PATH:$(pwd)/dnss-tools/target/appassembler/bin:

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
CWD="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

JSON=0
SKILLICONS=0
CONTEXT=0
SKIP_EXTRACT_PAK=0
SKIP_EXTRACT_DNT=0
SKIP_MVN=0

while test $# -gt 0
do
    case "$1" in
        --json) JSON=1
            ;;
        --skillicons) SKILLICONS=1
            ;;
        --context) CONTEXT=1
            ;;
        --skip-extract-pak) SKIP_EXTRACT_PAK=1
            ;;
        --skip-extract-dnt) SKIP_EXTRACT_DNT=1
            ;;
        --skip-mvn) SKIP_MVN=1
            ;;
        *)
            echo UNKNOWN OPTION $1
            exit 1
            ;;
    esac
    shift
done

if [[ ${SKIP_MVN} -eq 0 ]]; then
    mvn clean install -DskipTests --projects dnss-tools --also-make
fi

if [[ ${SKIP_EXTRACT_PAK} -eq 0 ]]; then
    pak
fi

if [[ ${SKIP_EXTRACT_DNT} -eq 0 ]]; then
    dnt
    cd /cygdrive/e/resource/sql
    export PGPASSWORD=dnss
    for sql in *; do
      psql -h localhost -U dnss -d dnss < ${sql}
    done
fi

if [[ ${CONTEXT} -eq 1 ]]; then
    ruby ${CWD}/dnss-tools/src/main/ruby/context_generator.rb
fi

if [[ ${JSON} -eq 1 ]]; then
    cd ${CWD}/dnss-web/src/main/webapp/resources/json/min
    echo Removing $(ls)
    rm -f *
    ruby ${CWD}/dnss-tools/src/main/ruby/json_generator.rb
    version=$(ruby ${CWD}/dnss-tools/src/main/ruby/update_properties.rb json)
    for file in *; do
        echo Renaming $file to ${version}-${file}
        mv ${file} ${version}-${file}
    done
    git add *
fi

if [[ ${SKILLICONS} -eq 1 ]]; then
    cd ${CWD}/dnss-web/src/main/webapp/resources/images/skillicons
    echo Removing $(ls)
    rm -f *
    cd /cygdrive/e/resource/ui/mainbar
    echo Formatting $(ls skillicon*.dds) to PNG
    mogrify -format png skillicon*.dds
    echo Cropping $(ls skillicon*.png)
    mogrify -crop 500x550+0+0 +repage +repage skillicon*.png # 550 = 50px * 11 rows
    for png in skillicon*.png; do
        echo pngcrush -ow ${png}
        pngcrush -ow ${png} >/dev/null
    done
    cd -
    echo Copying over $(ls /cygdrive/e/resource/ui/mainbar/skillicon*.png) to $(pwd)
    cp -f /cygdrive/e/resource/ui/mainbar/skillicon*.png .
    version=$(ruby ${CWD}/dnss-tools/src/main/ruby/update_properties.rb skillicon)
    for file in *; do
        echo Renaming ${file} to ${version}_${file}
        mv ${file} ${version}_${file}
    done
    git add *
fi